import Head from "next/head";
import axios from "axios";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";

export default function Home() {
  const [user, setUser] = useState({});
  useEffect(() => {
    const getUser = async () => {
      // Get the token from client-side storage and pass in request
      const { data } = await axios.get("/api/user");

      setUser(data);
    };
    getUser();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>NextJS Playground</h1>
        <h2>Test GET request</h2>
        <p>
          Current user:
          {user?.name}
        </p>
        <p>
          Current email:
          {user.email}
        </p>
      </main>
    </div>
  );
}
