import Head from "next/head";
import axios from "axios";
import styles from "../styles/Home.module.css";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Home() {
  const [users, setUser] = useState([]);
  useEffect(() => {
    const getUser = async () => {
      // Get the token from client-side storage and pass in request
      const { data } = await axios.get("/api/user");

      setUser(data);
    };
    getUser();
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>NextJS Playground</h1>
        <br />
        <Link href="/new"> Click to add a user</Link>
        <Link href="/remove"> Click to remove a user</Link>
        <h2>Test GET request</h2>
        <h2>All users</h2>
        <table style={{ borderCollapse: "separate", borderSpacing: "5em" }}>
          <thead>
            <tr>
              <th>Id</th>
              <th>Name</th>
              <th>Email</th>
            </tr>
          </thead>
          <tbody>
            {users &&
              users.map((user) => (
                <tr key={user.name}>
                  <td>{user.id}</td>
                  <td>{user.name}</td>
                  <td>{user.email}</td>
                </tr>
              ))}
          </tbody>
        </table>
      </main>
    </div>
  );
}
